### ISSUE TITLE
RTX A6000 do not support FP64

### ISSUE THREAD

**Issue by btravouillon** [guilbaults/slurm-job-exporter#18]
## Description

The service cannot start on a node with RTX A6000 GPUs.

```
# nvidia-smi -L
GPU 0: NVIDIA RTX A6000 (UUID: GPU-fcc7629a-445d-6296-c659-263fac8dedf7)
GPU 1: NVIDIA RTX A6000 (UUID: GPU-fb34d11f-e7fa-7dd5-058a-4a42dacca473)
GPU 2: NVIDIA RTX A6000 (UUID: GPU-e28a269b-afe2-016d-2173-ca8050cd7ec8)
GPU 3: NVIDIA RTX A6000 (UUID: GPU-90aae9dd-ac23-55fc-bd6b-8e3ae6d8872e)
GPU 4: NVIDIA RTX A6000 (UUID: GPU-5bb28798-1a4d-9463-4753-5d232dc1aca4)
GPU 5: NVIDIA RTX A6000 (UUID: GPU-a934acad-40ec-4180-e1a7-f5cb4fa15181)
GPU 6: NVIDIA RTX A6000 (UUID: GPU-6639da16-06fe-d8ac-ef2b-e567584bd753)
GPU 7: NVIDIA RTX A6000 (UUID: GPU-c97e1cb4-22f3-5ef3-681f-9a4b93b239f8)
```

```
Nov 20 11:53:11 cn-a600 systemd[1]: Started Slurm-job-exporter.
Nov 20 11:53:11 cn-a600 python3[10638]: Traceback (most recent call last): 
Nov 20 11:53:11 cn-a600 python3[10638]:   File "/opt/slurm-job-exporter/slurm-job-exporter.py", line 559, in <module>
Nov 20 11:53:11 cn-a600 python3[10638]:     APP = make_wsgi_app(SlurmJobCollector(dcgm_update_interval=ARGS.dcgm_update_int
Nov 20 11:53:11 cn-a600 python3[10638]:   File "/opt/slurm-job-exporter/slurm-job-exporter.py", line 155, in __init__
Nov 20 11:53:11 cn-a600 python3[10638]:     self.group.samples.WatchFields(self.field_group, dcgm_update_interval * 1000 * 
Nov 20 11:53:11 cn-a600 python3[10638]:   File "/usr/local/dcgm/bindings/python3/DcgmGroup.py", line 105, in WatchFields
Nov 20 11:53:11 cn-a600 python3[10638]:     ret = dcgm_agent.dcgmWatchFields(self._dcgmHandle.handle, self._groupId, fieldG
Nov 20 11:53:11 cn-a600 python3[10638]:   File "/usr/local/dcgm/bindings/python3/dcgm_agent.py", line 52, in wrapper
Nov 20 11:53:11 cn-a600 python3[10638]:     return fn(*newargs, **newkwargs)
Nov 20 11:53:11 cn-a600 python3[10638]:   File "/usr/local/dcgm/bindings/python3/dcgm_agent.py", line 457, in dcgmWatchFiel
Nov 20 11:53:11 cn-a600 python3[10638]:     dcgm_structs._dcgmCheckReturn(ret)
Nov 20 11:53:11 cn-a600 python3[10638]:   File "/usr/local/dcgm/bindings/python3/dcgm_structs.py", line 619, in _dcgmCheckR
Nov 20 11:53:11 cn-a600 python3[10638]:     raise DCGMError(ret)
Nov 20 11:53:11 cn-a600 python3[10638]: dcgm_structs.DCGMError_NotSupported: Feature not supported
Nov 20 11:53:11 cn-a600 systemd[1]: slurm-job-exporter.service: Main process exited, code=exited, status=1/FAILURE
Nov 20 11:53:11 cn-a600 systemd[1]: slurm-job-exporter.service: Failed with result 'exit-code'.
```

In `/var/log/nv-hostengine.log`:
```
2023-11-20 11:53:11.556 ERROR [50151:50229] [[Profiling]] FieldId {1006} is not supported for GPU 0 [/workspaces/dcgm-rel_dcgm_3_3-postmerge/dcgm_private/modules/profiling/DcgmModuleProfiling.cpp:2709] [DcgmNs::Modules::Profiling::DcgmModuleProfiling::ConvertFieldIdsToMetricIds]
2023-11-20 11:53:11.556 ERROR [50151:50229] [[Profiling]] Unable to reconfigure LOP metric watches for GpuId {0} [/workspaces/dcgm-rel_dcgm_3_3-postmerge/dcgm_private/modules/profiling/DcgmModuleProfiling.cpp:2740] [DcgmNs::Modules::Profiling::DcgmModuleProfiling::ChangeWatchState]
2023-11-20 11:53:11.556 ERROR [50151:50160] DCGM_PROFILING_SR_WATCH_FIELDS failed with -6 [/workspaces/dcgm-rel_dcgm_3_3-postmerge/dcgmlib/src/DcgmHostEngineHandler.cpp:3710] [DcgmHostEngineHandler::WatchFieldGroup]
```

When I comment out [dcgm_fields.DCGM_FI_PROF_PIPE_FP64_ACTIVE: 'fp64_active'](https://github.com/guilbaults/slurm-job-exporter/blob/v0.2.0/slurm-job-exporter.py#L141), the service can start successfully.

## Info

- slurm-job-exporter: 0.2.0
- datacenter-gpu-manager: 3.3.0
- NVIDIA driver: 535.104.12

**Comment by guilbaults** [comment]
Check this PR (https://github.com/guilbaults/slurm-job-exporter/pull/19), I will need the exact GPU name reported by DCGM to add it to the list.
