### ISSUE TITLE
DCGM compatibility with Nvidia L4 GPU

### ISSUE THREAD

**Issue by blixuga** [guilbaults/slurm-job-exporter#24]
slurm-job-exporter v0.4.1
the compute node is a Dell R7615, with 4 x Nvidia L4 GPU
Rocky 8.8
datacenter-gpu-manager-3.3.5-1.x86_64
nvidia-driver-535.86.10-1.el8.x86_64

I have tried this with our A100 nodes and works fine, but on our new L4 node
```
/usr/bin/slurm-job-exporter 
Detected gpu NVIDIA L4 with ID 0
Detected gpu NVIDIA L4 with ID 1
Detected gpu NVIDIA L4 with ID 2
Detected gpu NVIDIA L4 with ID 3
Traceback (most recent call last):
  File "/usr/bin/slurm-job-exporter", line 616, in <module>
    APP = make_wsgi_app(SlurmJobCollector(dcgm_update_interval=ARGS.dcgm_update_interval))
  File "/usr/bin/slurm-job-exporter", line 173, in __init__
    self.group.samples.WatchFields(self.field_group, dcgm_update_interval * 1000 * 1000, dcgm_update_interval * 2.0, 0)
  File "/usr/local/dcgm/bindings/python3/DcgmGroup.py", line 105, in WatchFields
    ret = dcgm_agent.dcgmWatchFields(self._dcgmHandle.handle, self._groupId, fieldGroup.fieldGroupId, updateFreq, maxKeepAge, maxKeepSamples)
  File "/usr/local/dcgm/bindings/python3/dcgm_agent.py", line 52, in wrapper
    return fn(*newargs, **newkwargs)
  File "/usr/local/dcgm/bindings/python3/dcgm_agent.py", line 457, in dcgmWatchFields
    dcgm_structs._dcgmCheckReturn(ret)
  File "/usr/local/dcgm/bindings/python3/dcgm_structs.py", line 619, in _dcgmCheckReturn
    raise DCGMError(ret)
dcgm_structs.DCGMError_NotSupported: Feature not supported
```
Output from `dcgmi discovery -l`
```
dcgmi discovery -l
4 GPUs found.
+--------+----------------------------------------------------------------------+
| GPU ID | Device Information                                                   |
+--------+----------------------------------------------------------------------+
| 0      | Name: NVIDIA L4                                                      |
|        | PCI Bus ID: 00000000:01:00.0                                         |
|        | Device UUID: GPU-278b8f6c-2b4e-78c6-c7be-f2a4ac840d0c                |
+--------+----------------------------------------------------------------------+
| 1      | Name: NVIDIA L4                                                      |
|        | PCI Bus ID: 00000000:02:00.0                                         |
|        | Device UUID: GPU-ba864725-9c43-c3c7-7dd2-f59e9a472079                |
+--------+----------------------------------------------------------------------+
| 2      | Name: NVIDIA L4                                                      |
|        | PCI Bus ID: 00000000:42:00.0                                         |
|        | Device UUID: GPU-8b83ae22-27f8-8d56-0e0f-8099671b1142                |
+--------+----------------------------------------------------------------------+
| 3      | Name: NVIDIA L4                                                      |
|        | PCI Bus ID: 00000000:C4:00.0                                         |
|        | Device UUID: GPU-465fbc64-2214-dab6-8084-2fa90f00dfc8                |
+--------+----------------------------------------------------------------------+
0 NvSwitches found.
+-----------+
| Switch ID |
+-----------+
+-----------+
0 CPUs found.
+--------+----------------------------------------------------------------------+
| CPU ID | Device Information                                                   |
+--------+----------------------------------------------------------------------+
+--------+----------------------------------------------------------------------+
```
Output from `nvidia-smi -L`
```
GPU 0: NVIDIA L4 (UUID: GPU-278b8f6c-2b4e-78c6-c7be-f2a4ac840d0c)
GPU 1: NVIDIA L4 (UUID: GPU-ba864725-9c43-c3c7-7dd2-f59e9a472079)
GPU 2: NVIDIA L4 (UUID: GPU-8b83ae22-27f8-8d56-0e0f-8099671b1142)
GPU 3: NVIDIA L4 (UUID: GPU-465fbc64-2214-dab6-8084-2fa90f00dfc8)
```

"ERROR|WARN" Output from debug log of `nv-hostengine --log-level debug --f /tmp/host.debug.log -n`
```
2024-04-16 13:32:42.479 WARN  [64200:64202] Got 0 entities from GetAllEntitiesOfEntityGroup() of eg 4 [/workspaces/dcgm-rel_dcgm_3_3-postmerge/dcgmlib/src/DcgmGroupManager.cpp:160] [DcgmGroupManager::AddAllEntitiesToGroup]
2024-04-16 13:32:42.517 ERROR [64200:64219] [[Profiling]] FieldId {1006} is not supported for GPU 0 [/workspaces/dcgm-rel_dcgm_3_3-postmerge/dcgm_private/modules/profiling/DcgmModuleProfiling.cpp:2709] [DcgmNs::Modules::Profiling::DcgmModuleProfiling::ConvertFieldIdsToMetricIds]
2024-04-16 13:32:42.517 ERROR [64200:64219] [[Profiling]] Unable to reconfigure LOP metric watches for GpuId {0} [/workspaces/dcgm-rel_dcgm_3_3-postmerge/dcgm_private/modules/profiling/DcgmModuleProfiling.cpp:2740] [DcgmNs::Modules::Profiling::DcgmModuleProfiling::ChangeWatchState]
2024-04-16 13:32:42.517 ERROR [64200:64202] DCGM_PROFILING_SR_WATCH_FIELDS failed with -6 [/workspaces/dcgm-rel_dcgm_3_3-postmerge/dcgmlib/src/DcgmHostEngineHandler.cpp:3710] [DcgmHostEngineHandler::WatchFieldGroup]
```

**Comment by blixuga** [comment]
Just tested a installing a node with the `nvidia-driver:550-dkms` module and `fm` profile, then installing dcgm.  Same results on these versions:

version info:
```
rpm -qa |grep datacenter
datacenter-gpu-manager-3.3.5-1.x86_64

rpm -qa |grep nvidia
dnf-plugin-nvidia-2.0-1.el8.noarch
nvidia-driver-cuda-550.54.15-1.el8.x86_64
libnvidia-nscq-550-550.54.15-1.x86_64
nvidia-driver-libs-550.54.15-1.el8.x86_64
nvidia-libXNVCtrl-550.54.15-1.el8.x86_64
nvidia-fabric-manager-550.54.15-1.x86_64
nvidia-driver-NVML-550.54.15-1.el8.x86_64
nvidia-libXNVCtrl-devel-550.54.15-1.el8.x86_64
nvidia-persistenced-550.54.15-1.el8.x86_64
kmod-nvidia-latest-dkms-550.54.15-1.el8.x86_64
nvidia-driver-devel-550.54.15-1.el8.x86_64
nvidia-modprobe-550.54.15-1.el8.x86_64
nvidia-driver-cuda-libs-550.54.15-1.el8.x86_64
nvidia-driver-NvFBCOpenGL-550.54.15-1.el8.x86_64
nvidia-driver-550.54.15-1.el8.x86_64
nvidia-xconfig-550.54.15-1.el8.x86_64
nvidia-kmod-common-550.54.15-1.el8.noarch
nvidia-settings-550.54.15-1.el8.x86_64
```

**Comment by guilbaults** [comment]
Hi,

Field 1006 is PROF_PIPE_FP64_ACTIVE, this sounds like FP64 is not supported on that GPU, similar to the A6000.

Please try this branch:
https://github.com/guilbaults/slurm-job-exporter/compare/L4

**Comment by blixuga** [comment]
> Hi,
> 
> Field 1006 is PROF_PIPE_FP64_ACTIVE, this sounds like FP64 is not supported on that GPU, similar to the A6000.
> 
> Please try this branch: https://github.com/guilbaults/slurm-job-exporter/compare/L4

You are correct, this GPU does not support FP64.  I tried the change, and that worked perfectly!
Thanks for the quick update!
